### ISSUE TITLE
動画削除ではないエラーなどが出ても削除動画に転送されてしまう

### ISSUE THREAD

**Issue by okaits** [MizuiMiduki/niconico-PublicCemetery#4]
動画を見ようとしたら、サーバーが混雑してて見れなくて、少し待とうと思ったら削除動画に転送されてしまいました。

**Comment by okaits** [comment]
削除動画にアクセスしようとした時に混雑エラーが出ると、さらに削除動画に転送されてしまうので、DoS攻撃みたいになってしまってます

**Comment by MizuiMiduki** [comment]
報告ありがとうございます。
こちらでも把握していて、削除動画であることのみを検知できる手段を模索中です。

**Comment by MizuiMiduki** [comment]
R2.2でこの不具合は修正しました
